select * from SALES."Dream Craft"."`OFFICES`";

UPDATE SALES."Dream Craft"."`OFFICES`"
SET "`STATE`" = 'NA'
WHERE "`STATE`" IS NULL;

select * from SALES."Dream Craft"."`CUSTOMERS`";

UPDATE SALES."Dream Craft"."`CUSTOMERS`"
SET "`STATE`" = 'NA'
WHERE "`STATE`" IS NULL;

UPDATE SALES."Dream Craft"."`CUSTOMERS`"
SET "`SALESREPEMPLOYEENUMBER`" = 0
WHERE "`SALESREPEMPLOYEENUMBER`" IS NULL;

select * from SALES."Dream Craft"."`ORDERS`";

UPDATE SALES."Dream Craft"."`ORDERS`"
SET "`COMMENTS`" = 'NA'
WHERE "`COMMENTS`" IS NULL;

UPDATE SALES."Dream Craft"."`ORDERS`"
SET "`SHIPPEDDATE`" = '0'
WHERE "`SHIPPEDDATE`" IS NULL;

select * from SALES."Dream Craft"."`EMPLOYEES`";

UPDATE SALES."Dream Craft"."`EMPLOYEES`"
SET "`REPORTSTO`" = '0'
WHERE "`REPORTSTO`" IS NULL;

select * from SALES."Dream Craft"."`PRODUCTS`";

ALTER TABLE SALES."Dream Craft"."`PRODUCTS`"
ADD "`MARKUP_PERCENTAGE`" DOUBLE;

UPDATE SALES."Dream Craft"."`PRODUCTS`"
SET "`MARKUP_PERCENTAGE`" = ROUND((`MSRP`-`BUYPRICE`)/`BUYPRICE` * 100, 2);

select * from SALES."Dream Craft"."`ORDERDETAILS`";

ALTER TABLE SALES."Dream Craft"."`ORDERDETAILS`"
ADD "`TOTAL_COST`" DECIMAL(10,2);

UPDATE SALES."Dream Craft"."`ORDERDETAILS`"
SET "`TOTAL_COST`" = "`QUANTITYORDERED`" * "`PRICEEACH`";

CREATE VIEW SALES_DETAILS AS
SELECT C.`CUSTOMERNUMBER`, O.`ORDERNUMBER`, C.`COUNTRY`, OD.`QUANTITYORDERED`, OD.`PRICEEACH`
FROM SALES."Dream Craft"."`ORDERS`" O
JOIN SALES."Dream Craft"."`CUSTOMERS`" C
ON O.`CUSTOMERNUMBER` = C.`CUSTOMERNUMBER`
JOIN SALES."Dream Craft"."`ORDERDETAILS`" OD
ON O.`ORDERNUMBER` = OD.`ORDERNUMBER`
ORDER BY OD.`QUANTITYORDERED` DESC;

select * from SALES_DETAILS;

CREATE VIEW HIGH_VALUE_CUSTOMERS AS 
SELECT C.`CUSTOMERNUMBER`, C.`CUSTOMERNAME`, C.`COUNTRY`, P.`CHECKNUMBER`, P.`AMOUNT`
FROM SALES."Dream Craft"."`CUSTOMERS`" C
JOIN SALES."Dream Craft"."`PAYMENTS`" P
ON C.`CUSTOMERNUMBER` = P.`CUSTOMERNUMBER`;

select * from HIGH_VALUE_CUSTOMERS;

CREATE OR REPLACE PROCEDURE GET_MARKUP_HIGHER (number_1 INTEGER)
RETURNS INTEGER NOT NULL
LANGUAGE SQL
AS
$$
DECLARE
  markup_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO markup_count FROM SALES."Dream Craft"."`PRODUCTS`"
  WHERE "`MARKUP_PERCENTAGE`" > :number_1;
  RETURN markup_count;
END;
$$;

CALL SALES."Dream Craft".GET_MARKUP_HIGHER(50);

CREATE OR REPLACE PROCEDURE SALES."Dream Craft".GET_HIGHCREDIT_CUSTOMERS (CL NUMBER)
RETURNS TABLE(CUSTOMERNAME VARCHAR(50), CREDIT FLOAT)
LANGUAGE SQL
AS
$$
DECLARE
  V_RESULTS RESULTSET;
BEGIN
  V_RESULTS := (
    SELECT "`CUSTOMERNAME`" AS CUSTOMERNAME, "`CREDITLIMIT`" AS CREDIT
    FROM SALES."Dream Craft"."`CUSTOMERS`"
    WHERE "`CREDITLIMIT`" > :CL);
  RETURN TABLE(V_RESULTS);
END;
$$;

CALL SALES."Dream Craft".GET_HIGHCREDIT_CUSTOMERS(100000);

CREATE OR REPLACE FILE FORMAT SALES."Dream Craft".MY_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1;

CREATE OR REPLACE STAGE SALES."Dream Craft".DATA_STAGE
  FILE_FORMAT = SALES."Dream Craft".MY_CSV_FORMAT;

COPY INTO '@SALES."Dream Craft".DATA_STAGE/Offices/'
FROM SALES."Dream Craft"."`OFFICES`"
OVERWRITE = TRUE
DETAILED_OUTPUT = TRUE;

select * from SALES."Dream Craft"."`CUSTOMERS`";

DELETE FROM SALES."Dream Craft"."`CUSTOMERS`"
WHERE `CUSTOMERNUMBER` = 112;

select * from SALES."Dream Craft"."`CUSTOMERS`" AT(OFFSET => -2400);

select * from SALES."Dream Craft"."`CUSTOMERS`" AT(OFFSET => -2400)
WHERE SALES."Dream Craft"."`CUSTOMERS`"."`CUSTOMERNUMBER`" = 112;

INSERT INTO SALES."Dream Craft"."`CUSTOMERS`"
SELECT * FROM SALES."Dream Craft"."`CUSTOMERS`" AT (OFFSET => -2400)
WHERE "`CUSTOMERNUMBER`" = 112;